FROM centos:latest
# 特権モードで起動する場合
# docker run -d --privileged -p 8080:80  centos:1.0 /sbin/init
# https://cstoku.dev/posts/2016/ad2016-docker-vm-gs/
# 次に、nginx サービスの設定
# sh-4.2# touch /lib/systemd/system/nginx.service 
# sh-4.2# vi /lib/systemd/system/nginx.service
# 下記内容を設定する。"nginx systemdで検索：nginx systemd service fileがhit"
# https://www.nginx.com/resources/wiki/start/topics/examples/systemd/
# そして、nginxサービス起動
# sh-4.2# systemctl start nginx

#php-fpm install
RUN yum install -y http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
RUN yum --enablerepo=remi-php73 install -y php-fpm

#nginx install
RUN yum install -y epel-release
RUN yum install -y wget
RUN wget http://nginx.org/download/nginx-1.15.12.tar.gz
RUN tar -zxvf nginx-1.15.12.tar.gz
RUN yum groupinstall -y "Development Tools"
RUN yum install -y pcre pcre-devel zlib zlib-devel openssl openssl-devel
RUN yum install -y gd-devel

#php-fpm config
RUN sed -i -e '38s/.*/listen = 127.0.0.1:9000/' /etc/php-fpm.d/www.conf 

#nginx config
WORKDIR /nginx-1.15.12/
RUN ./configure --sbin-path=/usr/bin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --with-pcre --pid-path=/var/run/nginx.pid --with-http_ssl_module --with-http_image_filter_module=dynamic --modules-path=/etc/nginx/modules
RUN make
RUN make install

COPY ./info.php /sites/
COPY ./demo/ /sites/
COPY ./nginx.conf /etc/nginx/
COPY ./nginx.service /lib/systemd/system/
EXPOSE 80

CMD nginx -g "daemon off;"